name: Build and Deploy Dashboard
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build Dashboard
        run: npx quasar build -m pwa
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy-production:
    name: 'Deploy de Teste em Desenvolvimento'
    if: ${{ github.ref_name == 'master'}}
    needs: build
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-develop:
    name: 'Deploy de Teste em Desenvolvimento'
    if: ${{ github.ref_name == 'develop'}}
    needs: build
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          QENV: ${{ secrets.QENV }}
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
          DEV_AUTH_DOMAIN: ${{ secrets.DEV_AUTH_DOMAIN }}
          DEV_DATA_BASE_URL: ${{ secrets.DEV_DATA_BASE_URL }}
          DEV_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
          DEV_STORAGE_BUCKET: ${{ secrets.DEV_STORAGE_BUCKET }}
          DEV_MESSAGING_SENDER_ID: ${{ secrets.DEV_MESSAGING_SENDER_ID }}
          DEV_APP_ID: ${{ secrets.DEV_APP_ID }}
          DEV_MEASUREMENT_ID: ${{ secrets.DEV_MEASUREMENT_ID }}
          DEV_GITHUB_CLIENT_SECRET: ${{ secrets.DEV_GITHUB_CLIENT_SECRET }}
          DEV_GITHUB_CLIENT_ID: ${{ secrets.DEV_GITHUB_CLIENT_ID }}
          DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.DEV_PROJECT_ID}}
